### PR TITLE
Fixes for Julia v0.7

### PR DESCRIPTION
**Pull request by juliohm**
This PR is an experiment. I am trying to get rid of the Images.jl dependency altogether, which is too big for an essential package like this.

### CODE REVIEW

**Comment by juliohm** [comment]
With the recent changes merged in `ColorTypes.jl` `ColorVectorSpace.jl` and `ImageMagick.jl` we are now ready to start eliminating the `Images.jl` dependency on this project. The tests after this last commit will pass, but the PR is not ready.

I will work on moving the distance definitions to `ImageDistances.jl` and then will add it as a dependency in `VisualRegressionTests.jl`.

**Comment by daschw** [comment]
Sounds great! Thanks so much for this!

**Comment by juliohm** [comment]
This is ready. Could you please merge and tag? I will submit another PR in the future to remove the ImageFiltering.jl dependency.

**Comment by mkborregaard** [comment]
Absolutely, thanks @juliohm !

**Pull request merged**
