### PR TITLE
Fix typo in info message

### PR DESCRIPTION
**Pull request by juliohm**
Missed this typo, sorry! Could you please merge, and update the release on METADATA?

### CODE REVIEW

**Comment by juliohm** [comment]
And we also need to fix the optional dependency with Gtk, in Julia v0.7 I don't know how to do that. It seems like we can't import Gtk optionally without explicitly adding it to the REQUIRE as a dependency, bummer. Will ask in the slack channel.

**Comment by juliohm** [comment]
Ok, I've added Gtk as a dependency temporarily so that other packages that rely on VisualRegressionTests.jl can be updated. In the future, we should refactor the code to try use Requires.jl

Please review to see if everything looks ok, and then we could merge, and update the release on METADATA

**Comment by juliohm** [comment]
@daschw could you maybe update this PR since you are already familiar with the Requires.jl mechanism? I can try look into it after next Tuesday.

**Comment by daschw** [comment]
Sure, no problem. I think I can find some time until tomorrow.

**Pull request merged**
